export const movies_list = [{
    "imdb_code": "tt5319866",
    "title": "Slamma Jamma",
    "title_long": "Slamma Jamma (2017)",
    "slug": "slamma-jamma-2017",
    "year": 2017,
    "rating": 6.1,
    "runtime": 104,
    "genres": [
      "Drama",
      "Sport"
    ],
    "summary": "Wrongfully accused and sent to prison, a former basketball star prepares for the national slam dunk competition while finding redemption in himself and in those he loves.",
    "description_full": "Wrongfully accused and sent to prison, a former basketball star prepares for the national slam dunk competition while finding redemption in himself and in those he loves.",
    "synopsis": "Wrongfully accused and sent to prison, a former basketball star prepares for the national slam dunk competition while finding redemption in himself and in those he loves.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/slamma_jamma_2017/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/slamma_jamma_2017/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/slamma_jamma_2017/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0095497",
    "title": "The Last Temptation of Christ",
    "title_long": "The Last Temptation of Christ (1988)",
    "slug": "the-last-temptation-of-christ-1988",
    "year": 1988,
    "rating": 7.6,
    "runtime": 164,
    "genres": [
      "Drama"
    ],
    "summary": "The carpenter, Jesus of Nazareth, tormented by the temptations of demons, the guilt of making crosses for the Romans, pity for men and the world, and the constant call of God, sets out to find what God wills for Him. But as His mission nears fulfillment, He must face the greatest temptation; the normal life of a good man. Based, not on the Gospels, but on Nikos Kazantzakis' novel of the same name.",
    "description_full": "The carpenter, Jesus of Nazareth, tormented by the temptations of demons, the guilt of making crosses for the Romans, pity for men and the world, and the constant call of God, sets out to find what God wills for Him. But as His mission nears fulfillment, He must face the greatest temptation; the normal life of a good man. Based, not on the Gospels, but on Nikos Kazantzakis' novel of the same name.",
    "synopsis": "The carpenter, Jesus of Nazareth, tormented by the temptations of demons, the guilt of making crosses for the Romans, pity for men and the world, and the constant call of God, sets out to find what God wills for Him. But as His mission nears fulfillment, He must face the greatest temptation; the normal life of a good man. Based, not on the Gospels, but on Nikos Kazantzakis' novel of the same name.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_last_temptation_of_christ_1988/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_last_temptation_of_christ_1988/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_last_temptation_of_christ_1988/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0106696",
    "title": "The Young Girls Turn 25",
    "title_long": "The Young Girls Turn 25 (1993)",
    "slug": "the-young-girls-turn-25-1993",
    "year": 1993,
    "rating": 7.1,
    "runtime": 64,
    "genres": [
      "Documentary",
      "Music"
    ],
    "summary": "A recital becomes part of the French culture; 25 years later the performers return to the village where it was first launched.",
    "description_full": "A recital becomes part of the French culture; 25 years later the performers return to the village where it was first launched.",
    "synopsis": "A recital becomes part of the French culture; 25 years later the performers return to the village where it was first launched.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_young_girls_turn_25_1993/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_young_girls_turn_25_1993/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_young_girls_turn_25_1993/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt7840894",
    "title": "Running Out of Time",
    "title_long": "Running Out of Time (2018)",
    "slug": "running-out-of-time-2018",
    "year": 2018,
    "rating": 0,
    "runtime": 13,
    "genres": [
      "Drama",
      "Thriller"
    ],
    "summary": "",
    "description_full": "",
    "synopsis": "",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/running_out_of_time_2018/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/running_out_of_time_2018/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/running_out_of_time_2018/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt9013956",
    "title": "Fish School 2",
    "title_long": "Fish School 2 (2019)",
    "slug": "fish-school-2-2019",
    "year": 2019,
    "rating": 0,
    "runtime": 0,
    "genres": [
      "Animation"
    ],
    "summary": "",
    "description_full": "",
    "synopsis": "",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/fish_school_2_2019/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/fish_school_2_2019/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/fish_school_2_2019/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt8706988",
    "title": "The Messenger",
    "title_long": "The Messenger (2019)",
    "slug": "the-messenger-2019",
    "year": 2019,
    "rating": 5.9,
    "runtime": 114,
    "genres": [
      "Action",
      "Drama",
      "History",
      "Thriller",
      "War"
    ],
    "summary": "Film about the lead up to the Polish uprising against German occupation at the end of the Second World War.",
    "description_full": "Film about the lead up to the Polish uprising against German occupation at the end of the Second World War.",
    "synopsis": "Film about the lead up to the Polish uprising against German occupation at the end of the Second World War.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_messenger_2019/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_messenger_2019/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_messenger_2019/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt2036416",
    "title": "You Are the Apple of My Eye",
    "title_long": "You Are the Apple of My Eye (2011)",
    "slug": "you-are-the-apple-of-my-eye-2011",
    "year": 2011,
    "rating": 7.6,
    "runtime": 109,
    "genres": [
      "Comedy",
      "Drama",
      "Romance"
    ],
    "summary": "A coming of age story featuring a group of Taiwanese teenagers/friends and their experience as they all fall in love with the same girl: Shen Jiayi, the star student of the school. A story about the complexities and bitter sweetness of high school life set in the backdrop of Taiwanese cultures and traditions.",
    "description_full": "A coming of age story featuring a group of Taiwanese teenagers/friends and their experience as they all fall in love with the same girl: Shen Jiayi, the star student of the school. A story about the complexities and bitter sweetness of high school life set in the backdrop of Taiwanese cultures and traditions.",
    "synopsis": "A coming of age story featuring a group of Taiwanese teenagers/friends and their experience as they all fall in love with the same girl: Shen Jiayi, the star student of the school. A story about the complexities and bitter sweetness of high school life set in the backdrop of Taiwanese cultures and traditions.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/you_are_the_apple_of_my_eye_2011/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/you_are_the_apple_of_my_eye_2011/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/you_are_the_apple_of_my_eye_2011/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0046876",
    "title": "Creature from the Black Lagoon",
    "title_long": "Creature from the Black Lagoon (1954)",
    "slug": "creature-from-the-black-lagoon-1954",
    "year": 1954,
    "rating": 7,
    "runtime": 79,
    "genres": [
      "Horror",
      "Sci-Fi"
    ],
    "summary": "A scientific expedition searching for fossils along the Amazon River discovers a prehistoric Gill-Man in the legendary Black Lagoon. The explorers capture the mysterious creature, but it breaks free. The Gill-Man returns to kidnap the lovely Kay, fiancée of one in the expedition, with whom it has fallen in love.",
    "description_full": "A scientific expedition searching for fossils along the Amazon River discovers a prehistoric Gill-Man in the legendary Black Lagoon. The explorers capture the mysterious creature, but it breaks free. The Gill-Man returns to kidnap the lovely Kay, fiancée of one in the expedition, with whom it has fallen in love.",
    "synopsis": "A scientific expedition searching for fossils along the Amazon River discovers a prehistoric Gill-Man in the legendary Black Lagoon. The explorers capture the mysterious creature, but it breaks free. The Gill-Man returns to kidnap the lovely Kay, fiancée of one in the expedition, with whom it has fallen in love.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/creature_from_the_black_lagoon_1954/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/creature_from_the_black_lagoon_1954/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/creature_from_the_black_lagoon_1954/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0099691",
    "title": "Graffiti Bridge",
    "title_long": "Graffiti Bridge (1990)",
    "slug": "graffiti-bridge-1990",
    "year": 1990,
    "rating": 4.4,
    "runtime": 90,
    "genres": [
      "Drama",
      "Music"
    ],
    "summary": "The unofficial sequel to 'Purple Rain' (1984). The Kid is now club owner and rival to Morris (Morris Day) who get into a fight for the Glam Slam Nightclub.",
    "description_full": "The unofficial sequel to 'Purple Rain' (1984). The Kid is now club owner and rival to Morris (Morris Day) who get into a fight for the Glam Slam Nightclub.",
    "synopsis": "The unofficial sequel to 'Purple Rain' (1984). The Kid is now club owner and rival to Morris (Morris Day) who get into a fight for the Glam Slam Nightclub.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/graffiti_bridge_1990/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/graffiti_bridge_1990/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/graffiti_bridge_1990/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt6436888",
    "title": "The Cage Fighter",
    "title_long": "The Cage Fighter (2017)",
    "slug": "the-cage-fighter-2017",
    "year": 2017,
    "rating": 5.9,
    "runtime": 81,
    "genres": [
      "Action",
      "Documentary",
      "Drama"
    ],
    "summary": "A blue-collar family man breaks the promise he'd made years ago to never fight again. Now forty years old, with a wife and four children who need him, Joe Carman risks everything-his marriage, his family, his health-to go back into the fighting cage and come to terms with his past.",
    "description_full": "A blue-collar family man breaks the promise he'd made years ago to never fight again. Now forty years old, with a wife and four children who need him, Joe Carman risks everything-his marriage, his family, his health-to go back into the fighting cage and come to terms with his past.",
    "synopsis": "A blue-collar family man breaks the promise he'd made years ago to never fight again. Now forty years old, with a wife and four children who need him, Joe Carman risks everything-his marriage, his family, his health-to go back into the fighting cage and come to terms with his past.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_cage_fighter_2017/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_cage_fighter_2017/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_cage_fighter_2017/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt5599692",
    "title": "Clash",
    "title_long": "Clash (2016)",
    "slug": "clash-2016",
    "year": 2016,
    "rating": 7.5,
    "runtime": 97,
    "genres": [
      "Drama",
      "Thriller",
      "War"
    ],
    "summary": "Set entirely in an 8m police truck, a number of detainees from different political and social backgrounds are brought together by their inevitable fate, during the turmoil that followed the ousting of former president Morsi from power.",
    "description_full": "Set entirely in an 8m police truck, a number of detainees from different political and social backgrounds are brought together by their inevitable fate, during the turmoil that followed the ousting of former president Morsi from power.",
    "synopsis": "Set entirely in an 8m police truck, a number of detainees from different political and social backgrounds are brought together by their inevitable fate, during the turmoil that followed the ousting of former president Morsi from power.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/clash_2016/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/clash_2016/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/clash_2016/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0194314",
    "title": "Romance",
    "title_long": "Romance (1999)",
    "slug": "romance-1999",
    "year": 1999,
    "rating": 5.3,
    "runtime": 84,
    "genres": [
      "Drama"
    ],
    "summary": "Although deeply in love with her boyfriend - and indeed sleeping in the same bed with him - a schoolteacher cannot handle the almost complete lack of intimacy he will allow. Increasingly frustrated, she gradually finds her sexual appetites leading her into ever more risky situations, including a developing one with the headmaster.",
    "description_full": "Although deeply in love with her boyfriend - and indeed sleeping in the same bed with him - a schoolteacher cannot handle the almost complete lack of intimacy he will allow. Increasingly frustrated, she gradually finds her sexual appetites leading her into ever more risky situations, including a developing one with the headmaster.",
    "synopsis": "Although deeply in love with her boyfriend - and indeed sleeping in the same bed with him - a schoolteacher cannot handle the almost complete lack of intimacy he will allow. Increasingly frustrated, she gradually finds her sexual appetites leading her into ever more risky situations, including a developing one with the headmaster.",
    "language": "English",
    "mpa_rating": "R",
    "small_cover_image": "https://yts.lt/assets/images/movies/romance_1999/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/romance_1999/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/romance_1999/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt1847672",
    "title": "Remainder",
    "title_long": "Remainder (2015)",
    "slug": "remainder-2015",
    "year": 2015,
    "rating": 5.7,
    "runtime": 103,
    "genres": [
      "Drama"
    ],
    "summary": "A London man who loses his memory when he's struck by a falling object develops a way to reconstruct his past.",
    "description_full": "A London man who loses his memory when he's struck by a falling object develops a way to reconstruct his past.",
    "synopsis": "A London man who loses his memory when he's struck by a falling object develops a way to reconstruct his past.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/remainder_2015/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/remainder_2015/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/remainder_2015/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0093215",
    "title": "Hot Pursuit",
    "title_long": "Hot Pursuit (1987)",
    "slug": "hot-pursuit-1987",
    "year": 1987,
    "rating": 5.8,
    "runtime": 93,
    "genres": [
      "Comedy"
    ],
    "summary": "Young Danny is following his rich girlfriend's family to the Caribbean. But suddenly he simply must take a chemistry test and cannot go with them. After they have left, he gets a leave from his professor and takes a plane to find them. But he is not quite sure where they are, and meets smugglers, crazy captains and murderers.",
    "description_full": "Young Danny is following his rich girlfriend's family to the Caribbean. But suddenly he simply must take a chemistry test and cannot go with them. After they have left, he gets a leave from his professor and takes a plane to find them. But he is not quite sure where they are, and meets smugglers, crazy captains and murderers.",
    "synopsis": "Young Danny is following his rich girlfriend's family to the Caribbean. But suddenly he simply must take a chemistry test and cannot go with them. After they have left, he gets a leave from his professor and takes a plane to find them. But he is not quite sure where they are, and meets smugglers, crazy captains and murderers.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/hot_pursuit_1987/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/hot_pursuit_1987/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/hot_pursuit_1987/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt1188996",
    "title": "My Name Is Khan",
    "title_long": "My Name Is Khan (2010)",
    "slug": "my-name-is-khan-2010",
    "year": 2010,
    "rating": 8,
    "runtime": 165,
    "genres": [
      "Drama"
    ],
    "summary": "Rizwan Khan, a Muslim from the Borivali section of Mumbai, suffers from Asperger's syndrome, a form of high-functioning autism that complicates socialization. The adult Rizwan marries a Hindu single mother, Mandira, in San Francisco. After 9/11, Rizwan is detained by authorities at LAX who mistake his disability for suspicious behavior. Following his arrest, he meets Radha, a therapist who helps him deal with his situation and his affliction. Rizwan then begins a journey to meet US President Bush to clear his name.",
    "description_full": "Rizwan Khan, a Muslim from the Borivali section of Mumbai, suffers from Asperger's syndrome, a form of high-functioning autism that complicates socialization. The adult Rizwan marries a Hindu single mother, Mandira, in San Francisco. After 9/11, Rizwan is detained by authorities at LAX who mistake his disability for suspicious behavior. Following his arrest, he meets Radha, a therapist who helps him deal with his situation and his affliction. Rizwan then begins a journey to meet US President Bush to clear his name.",
    "synopsis": "Rizwan Khan, a Muslim from the Borivali section of Mumbai, suffers from Asperger's syndrome, a form of high-functioning autism that complicates socialization. The adult Rizwan marries a Hindu single mother, Mandira, in San Francisco. After 9/11, Rizwan is detained by authorities at LAX who mistake his disability for suspicious behavior. Following his arrest, he meets Radha, a therapist who helps him deal with his situation and his affliction. Rizwan then begins a journey to meet US President Bush to clear his name.",
    "language": "English",
    "mpa_rating": "PG-13",
    "small_cover_image": "https://yts.lt/assets/images/movies/my_name_is_khan_2010/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/my_name_is_khan_2010/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/my_name_is_khan_2010/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt0068732",
    "title": "Images",
    "title_long": "Images (1972)",
    "slug": "images-1972",
    "year": 1972,
    "rating": 7.2,
    "runtime": 104,
    "genres": [
      "Drama",
      "Horror",
      "Mystery"
    ],
    "summary": "Like Polanski's heroine in Repulsion, Susannah York's character is one that is seemingly haunted by memories of undisclosed magnitude. These memories are perhaps rooted in some sort of past sexual turmoil that causes York's character to see men as inherently the same.",
    "description_full": "Like Polanski's heroine in Repulsion, Susannah York's character is one that is seemingly haunted by memories of undisclosed magnitude. These memories are perhaps rooted in some sort of past sexual turmoil that causes York's character to see men as inherently the same.",
    "synopsis": "Like Polanski's heroine in Repulsion, Susannah York's character is one that is seemingly haunted by memories of undisclosed magnitude. These memories are perhaps rooted in some sort of past sexual turmoil that causes York's character to see men as inherently the same.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/images_1972/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/images_1972/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/images_1972/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt6434022",
    "title": "Will You Be There?",
    "title_long": "Will You Be There? (2016)",
    "slug": "will-you-be-there-2016",
    "year": 2016,
    "rating": 7,
    "runtime": 111,
    "genres": [
      "Drama",
      "Fantasy",
      "Romance"
    ],
    "summary": "A surgeon (Kim Yun-Seok) doesn't have much time left due to a serious illness. His wish is to see his girlfriend who died in an accident 30 years ago. The surgeon gets 10 pills from a mysterious old man. The 10 pills allows him to travel in time to the past.",
    "description_full": "A surgeon (Kim Yun-Seok) doesn't have much time left due to a serious illness. His wish is to see his girlfriend who died in an accident 30 years ago. The surgeon gets 10 pills from a mysterious old man. The 10 pills allows him to travel in time to the past.",
    "synopsis": "A surgeon (Kim Yun-Seok) doesn't have much time left due to a serious illness. His wish is to see his girlfriend who died in an accident 30 years ago. The surgeon gets 10 pills from a mysterious old man. The 10 pills allows him to travel in time to the past.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/will_you_be_there_2016/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/will_you_be_there_2016/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/will_you_be_there_2016/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt8022928",
    "title": "Descendants 3",
    "title_long": "Descendants 3 (2019)",
    "slug": "descendants-3-2019",
    "year": 2019,
    "rating": 7.9,
    "runtime": 106,
    "genres": [
      "Adventure",
      "Family",
      "Musical"
    ],
    "summary": "The teenagers of Disney's most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring to join them at Auradon Prep.",
    "description_full": "The teenagers of Disney's most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring to join them at Auradon Prep.",
    "synopsis": "The teenagers of Disney's most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring to join them at Auradon Prep.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/descendants_3_2019/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/descendants_3_2019/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/descendants_3_2019/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt5178264",
    "title": "Life in the Doghouse",
    "title_long": "Life in the Doghouse (2018)",
    "slug": "life-in-the-doghouse-2018",
    "year": 2018,
    "rating": 8.6,
    "runtime": 84,
    "genres": [
      "Documentary"
    ],
    "summary": "LIFE IN THE DOG HOUSE will tell the inspiring stories of Danny and Ron's Rescue (501c3). The film will showcase their unique approach to dog rescue and adoption, which has enabled them to rescue and adopt out 10,000 dogs.",
    "description_full": "LIFE IN THE DOG HOUSE will tell the inspiring stories of Danny and Ron's Rescue (501c3). The film will showcase their unique approach to dog rescue and adoption, which has enabled them to rescue and adopt out 10,000 dogs.",
    "synopsis": "LIFE IN THE DOG HOUSE will tell the inspiring stories of Danny and Ron's Rescue (501c3). The film will showcase their unique approach to dog rescue and adoption, which has enabled them to rescue and adopt out 10,000 dogs.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/life_in_the_doghouse_2018/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/life_in_the_doghouse_2018/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/life_in_the_doghouse_2018/large-cover.jpg",
    "state": "ok",
  },
  {
    "imdb_code": "tt2358891",
    "title": "The Great Beauty",
    "title_long": "The Great Beauty (2013)",
    "slug": "the-great-beauty-2013",
    "year": 2013,
    "rating": 7.8,
    "runtime": 141,
    "genres": [
      "Drama"
    ],
    "summary": "Journalist Jep Gambardella has charmed and seduced his way through the lavish nightlife of Rome for decades. Since the legendary success of his one and only novel, he has been a permanent fixture in the city's literary and social circles, but when his sixty-fifth birthday coincides with a shock from the past, Jep finds himself unexpectedly taking stock of his life, turning his cutting wit on himself and his contemporaries, and looking past the extravagant nightclubs, parties, and cafés to find Rome in all its glory: a timeless landscape of absurd, exquisite beauty.",
    "description_full": "Journalist Jep Gambardella has charmed and seduced his way through the lavish nightlife of Rome for decades. Since the legendary success of his one and only novel, he has been a permanent fixture in the city's literary and social circles, but when his sixty-fifth birthday coincides with a shock from the past, Jep finds himself unexpectedly taking stock of his life, turning his cutting wit on himself and his contemporaries, and looking past the extravagant nightclubs, parties, and cafés to find Rome in all its glory: a timeless landscape of absurd, exquisite beauty.",
    "synopsis": "Journalist Jep Gambardella has charmed and seduced his way through the lavish nightlife of Rome for decades. Since the legendary success of his one and only novel, he has been a permanent fixture in the city's literary and social circles, but when his sixty-fifth birthday coincides with a shock from the past, Jep finds himself unexpectedly taking stock of his life, turning his cutting wit on himself and his contemporaries, and looking past the extravagant nightclubs, parties, and cafés to find Rome in all its glory: a timeless landscape of absurd, exquisite beauty.",
    "language": "English",
    "mpa_rating": "",
    "small_cover_image": "https://yts.lt/assets/images/movies/the_great_beauty_2013/small-cover.jpg",
    "medium_cover_image": "https://yts.lt/assets/images/movies/the_great_beauty_2013/medium-cover.jpg",
    "large_cover_image": "https://yts.lt/assets/images/movies/the_great_beauty_2013/large-cover.jpg",
    "state": "ok",
  }
]